export default {
	AppTitle: "سوسائٹی ایپ",
	WelcomeMsg: "خوش آمدید",
	LoginOrRegister: "لاگ ان یا رجسٹر کریں",
	Login: "لاگ ان کریں",
	Logout: "لاگ آوٹ کریں",
	Register: "اکاؤنٹ بنائیں",
	CreateAccount: "اپنا اکاؤنٹ بنائیں",
	WelcomeMsg2: "اگر آپ کو اپنے اکاؤنٹ میں اندراج یا لاگ ان کرنے میں دشواری ہو تو ، براہ کرم مدد کے لئے رابطہ کریں{{CONTACT}}",
	HouseNumber: "مکان نمبر منتخب کریں",
	NameTitle: "آپ کا نام اور عنوان",
	Password: "پاس ورڈ",
	RepeatPassword: "پاس ورڈ دوبارہ لکھیے",
	PhoneNumber: "رابطے کا فون نمبر",
	PhoneMessage: "اس فون نمبر پر توثیقی کوڈ بھیجا جائے گا۔",
	WhatsAppNumber: "واٹس ایپ نمبر (اگر مختلف ہے)",
	OwnerOrRental: "مالک / کرایہ دار",
	Owner: "میں گھر کا مالک ہوں",
	Rental: "میں اس گھر کا مالک نہیں (کرایے پر / مہمان)",
	CompleteRegistration: "رجسٹریشن مکمل کریں",
	Home: "Home",
	Notices: "اعلانات",
	Complaints: "شکایات",
	Complainant: "شکایت کنندہ",
	AddComplaint: "شکایت درج کروائیں",
	MyComplaints: "میری شکایات",
	Subject: "مضمون",
	Details: "تفصیلات",
	PrivateComplaint: "میری شکایت کو خفیہ رکھیں",
	PrivateComplaintMsg: "نجی شکایات صرف یونین کے ممبروں کو دکھائی جاتی ہیں اور دوسرے لوگ انہیں نہیں دیکھیں گے",
	SubmitComplaint: "شکایت درج کروائیں",
	ComplaintSubmitted: "آپ کی شکایت درج کردی گئی ہے",
	ComplaintDetails: "شکایت",
	SubmitFailed: "نیٹ ورک کی خرابی ، براہ کرم دوبارہ کوشش کریں",
	MyComplains: "میری شکایات",
	Directory: "ڈائریکٹری",
	Expenses: "اخراجات",
	ContactDirectory: "رابطہ ڈائریکٹری",
	ViewDetails: "تفصیلات دیکھیں",
	Day: "دن",
	Category: "قسم",
	Amount: "رقم",
	AddExpense: "اخراجات شامل کریں",
	ExpenseAdded: "اخراجات کا ریکارڈ شامل کر دیا گیا ہے",
	AddCollection: "رقم شامل کریں",
	LogoutConfirmation: "ایپ سے سائن آؤٹ کریں",
	ConfirmExit: "کیا آپ واقعی ایپ کو بند کرنا چاہتے ہیں؟",
	EnterSocietyCode: "اپنا سوسائٹی کوڈ درج کریں",
	SocietyCodeMessage: "کوڈ حاصل کرنے کے لئے اپنے سوسائٹی کے ایڈمنسٹریٹر سے رابطہ کریں",
	FloorPortion: "فرش / پورشن (اختیاری)",
	FloorPortionPlaceholder: "گراؤنڈ / پہلا وغیرہ",
	AddComplaintReply: "جواب دیں",
	ComplaintMessage: "شکایت جواب",
	SubmitComplaintReply:  "جواب دیں",
	ChangeComplaintStatus: "حالت تبدیل کریں",
	Status: "حالت",
	Created: "بنائی گئی",
	Message: "پیغام",
	From: "شکایت کنندہ",
	LastUpdate: "آخری تبدیلی",
	NoticeType: "قسم",
	NoticeExpiryDate: "نوٹس ختم ہونے کی تاریخ",
	NoticeAdded: "نوٹس شامل کردی گئی ہے",
	Collection: "رقم موصول ہوئی",
	Date: "تاریخ",
	Notes: "یاداشت",
	CollectionAdded: "رقم ریکارڈ شامل کر دیا گیا ہے",
	AddNotice: "نوٹس شامل کریں",
	EditContact: "ترمیم کریں",
	Designation: "عہدہ",
	UpdateContact: "رابطہ اپ ڈیٹ کریں",
	ContactUpdated: "رابطہ کی معلومات کو اپ ڈیٹ کر دیا گیا ہے",
	AllowExpense: "اخراجات کو شامل کرنے کی اجازت دیں",
	AllowCollection: "جمع کرنے کی اجازت دیں",
	AllowResponse: "شکایت کی حیثیت کو اپ ڈیٹ کرنے کی اجازت دیں",
	AllowDirectory: "صارف کے ریکارڈ میں ترمیم کی اجازت دیں",
	AllowNotice: "نوٹسز کو اپ ڈیٹ کرنے کی اجازت دیں",
	AllowPolls: "ووٹنگ پولس بنانے کی اجازت دیں",
	AllowPlanning: "پلاننگ بورڈ تک رسائی کی اجازت دیں",
	AllowWorkers: "کارکنوں کی فہرست کو اپ ڈیٹ کرنے کی اجازت دیں",
	AppLoading: "برائے مہربانی انتظار کریں...",
	AddVotingPoll: "ووٹنگ پول شامل کریں",
	PollExpiryDate: "ووٹنگ کی آخری تاریخ",
	PollAdded: "ووٹنگ پول کو شامل کر دیا گیا ہے",
	Title: "عنوان",
	VotingOptions: "جوابات",
	SubmitVote: "ووٹ جمع کروائیں",
	ViewResults: "نتائج دیکھیں",
	AddChoice: "چوائس شامل کریں",
	VotingPoll: "ووٹنگ پول",
	VoteSubmitted: "آپ کا ووٹ جمع کرا دیا گیا ہے",
	LastVotingDate: "ووٹنگ جاری ہے",
	VoteCount: "ووٹ",
	VotingCount: "اب تک کے نتائج",
	VoteChoice: "اپنی ووٹ جمع کروائیں",
	ConfirmVote: "اپنے ووٹ کی تصدیق کریں",
	SearchPlaceholder: "گھر ، نام یا نمبر کے ذریعہ تلاش کریں",
	ConfirmPhoneTitle: "رابطہ نمبر کی تصدیق کریں",
	MyProfile: "میری پروفائل",
	UpdateProfile: "اپ ڈیٹ",
	ProfileUpdated: "پروفائل کو اپ ڈیٹ کر دیا گیا ہے",
	NoticeMedia: "میڈیا فائل (اختیاری)",
	ChooseFile: "فائل منتخب کریں",
	NoFileChoosen: "کوئی میڈیا فائل منسلکہ نہیں ہے",
	TakePicture: "تصویر لیں",
	InvalidFileType: "غلط فائل کی قسم مہیا کی گئی",
	ShowPhoneNumber: "ڈائریکٹری میں میرا فون نمبر سوسائٹی کے تمام ممبروں کو دکھائیں",
	SelectOption: "ایک آپشن منتخب کریں",
	Edit: 'ترمیم',
	Delete: 'حذف کریں',
	Archive: 'اسے حذف کریں',
	DeleteEntry: 'اس اندراج کو حذف کریں؟',
	EnterAmount: 'نئی رقم درج کریں',
	NoticeUpdated: "نوٹس کامیابی کے ساتھ اپ ڈیٹ ہوا",
	Select: "منتخب کریں",
	Private: "نجی",
	EditNotice: "نوٹس میں ترمیم کریں",
	UpdateNotice: "نوٹس کو اپ ڈیٹ کریں",
	ArchiveNotice: "حذف کرنے سے یہ نوٹس فوری طور پر ختم ہوجائے گا",
	Information: "معلومات",
	SocietyWorkers: "کارکنان",
	ContactDirectoryMsg: "سوسائٹی کے رہائشیوں کا رابطہ ، جنہوں نے ایپ پر سائن اپ کیا ہے",
	SocietyWorkersMsg: "قریب موجود پلمبر ، بجلی دانوں اور دیگر کارکنوں کی فعال فہرست",
	InfoLastUpdated: "آخری ترمیم:",
	SocietyCode: "رسائی کوڈ",
	ViewAttachment: "منسلک فائل دیکھیں",
	WorkerSearchPlaceholder: "نام یا نمبر سے تلاش کریں",
	Optional: "اختیاری",
	WorkerType: "کارکن کی قسم",
	WorkerTypePlaceHolder: "پلمبر ،لکڑی کا کارکن وغیرہ",
	EditWorker: "ترمیم",
	WorkerInfoUpdated: "کارکن کی معلومات کو اپ ڈیٹ کر دیا گیا ہے",
	Image: "(اختیاری) تصویر",
	AddWorker: "ورکر شامل کریں",
	UpdateWorker: "اپ ڈیٹ کریں",
	Submit: "جمع کرائیں",
	Guidelines: "ہدایات",
	GuidelinesMsg: "معاشرے کے رہائشیوں کے لئے عمومی قواعد و ضوابط",
	DueDates: "مقررہ تاریخ",
	BulkMaintenance: "متعدد ریکارڈز",
	PerHouse: "فی ہاؤس",
	AddMaintenance: "شامل کریں",
	Month: "مہینہ",
	MonthNames: "جنوری فروری مارچ اپریل مئی جون جولائی اگست ستمبر اکتوبر دسمبر دسمبر",
	Houses: "گھروں کا مجموعہ",
	MaintenanceRecieved: "رقم موصول ہوئی",
	Collections: "مجموعہ",
	WorkersLeaves: "کارکن رخصت ریکارڈ",
	AddLeaveRecord: "رخصت ریکارڈ شامل کریں",
	SearchPlaceholder: "تلاش کریں",
	Name: "نام",
	Optional: "اختیاری",
	OperationSuccess: "ریکارڈ شامل کردیا گیا ہے",
	EditExpense: "اخراجات میں ترمیم کریں",
	ExpenseUpdated: "اخراجات کا ریکارڈ تبدیل کر دیا گیا ہے",
	DownloadComplete: "ڈاؤن لوڈ مکمل ہو گیا ہے",
	DownloadFailed: "ڈاؤن لوڈ ناکام ہو گیا",
	Downloading: "فائل ڈاؤن لوڈ ہو رہی ہے ..."
};