export default {
	AppTitle: "Home Society",
	WelcomeMsg: "Welcome",
	LoginOrRegister: "Login Or Register",
	Login: "Login",
	Logout: "Logout",
	Register: "Create Account",
	CreateAccount: "Create your account",
	WelcomeMsg2: "If you have difficulty in registering or logging into your account, please contact {{CONTACT}}",
	HouseNumber: "Select House Number",
	NameTitle: "Your Name & Title",
	Password: "Password",
	RepeatPassword: "Repeat Password",
	PhoneNumber: "Contact Phone Number",
	PhoneMessage: "A verification code will be sent to this phone number.",
	WhatsAppNumber: "WhatsApp Number (optional)",
	OwnerOrRental: "Own House / Rental",
	Owner: "I own the house",
	Rental: "I do not own this house (rental/guest)",
	CompleteRegistration: "Complete Registration",
	Home: "Home",
	Notices: "Notices",
	Complaints: "Complaints",
	Complainant: "Complainant",
	AddComplaint: "Add Complaint",
	MyComplaints: "My Complaints",
	Subject: "Subject",
	Details: "Details",
	PrivateComplaint: "Keep my complaint private",
	PrivateComplaintMsg: "Private complaints are shown only to union members and other people will not see them",
	SubmitComplaint: "Submit Complaint",
	ComplaintSubmitted: "Your complaint has been submitted successfuly",
	ComplaintDetails: "Complaint",
	SubmitFailed: "Error occured in submitting your request, please try again",
	MyComplains: "My Complains",
	Directory: "Directory",
	Expenses: "Expenses",
	ContactDirectory: "Contact Directory",
	ViewDetails: "View Details",
	Day: "Day",
	Category: "Category",
	Amount: "Amount",
	AddExpense: "Add Expense",
	ExpenseAdded: "Expense record was added successfully",
	AddCollection: "Add Collection",
	LogoutConfirmation: "Really logout?",
	ConfirmExit: "Are you sure you want to exit the app?",
	EnterSocietyCode: "Enter your Society Code",
	SocietyCodeMessage: "Contact your Society Administrator to receive the code",
	FloorPortion: "Floor / Portion (optional)",
	FloorPortionPlaceholder: "Ground / First etc",
	AddComplaintReply: "Add Reply",
	ComplaintMessage: "Complaint Reply",
	SubmitComplaintReply: "Send Reply",
	ChangeComplaintStatus: "Change Status",
	Status: "Status",
	Created: "Created",
	Message: "Message",
	From: "From",
	LastUpdate: "Updated",
	NoticeType: "Type",
	NoticeExpiryDate: "Notice Expiry Date",
	NoticeAdded: "Notice Successfully Added",
	Collection: "Collection",
	Date: "Date",
	Notes: "Notes",
	CollectionAdded: "Collection Record Added",
	AddNotice: "Add Notice",
	EditContact: "Edit Contact",
	Designation: "Designation",
	UpdateContact: "Update Contact",
	ContactUpdated: "Contact Information Updated",
	AllowExpense: "Allow adding expenses",
	AllowCollection: "Allow adding collections",
	AllowResponse: "Allow updating complaint status",
	AllowDirectory: "Allow editing user records",
	AllowNotice: "Allow updating notices",
	AllowPolls: "Allow creating voting polls",
	AllowPlanning: "Allow access to planning board",
	AllowWorkers: "Allow updating workers list",
	AppLoading: "Please wait...",
	AddVotingPoll: "Add Voting Poll",
	PollExpiryDate: "Last Voting Date",
	PollAdded: "Voting Poll has been added",
	Title: "Title",
	VotingOptions: "Choices",
	SubmitVote: "Submit Vote",
	ViewResults: "View Results",
	AddChoice: "Add Choice",
	VotingPoll: "Voting Poll",
	VoteSubmitted: "Your vote has been submitted",
	LastVotingDate: "Voting open till",
	VoteCount: "Votes",
	VotingCount: "Results so far",
	VoteChoice: "Submit your Vote",
	ConfirmVote: "Confirm your vote",
	SearchPlaceholder: "Search by house, name or number",
	ConfirmPhoneTitle: "Confirm contact number",
	MyProfile: "My Profile",
	UpdateProfile: "Update",
	ProfileUpdated: "Profile successfully updated",
	NoticeMedia: "Media file (optional)",
	ChooseFile: "Select File",
	NoFileChoosen: "No attachment",
	TakePicture: "Take Picture",
	InvalidFileType: "Wrong file type",
	ShowPhoneNumber: "Show my phone number in the directory to all society members",
	SelectOption: "Select an option",
	Edit: 'Edit',
	Delete: 'Delete',
	Archive: 'Archive',
	DeleteEntry: 'Delete this entry?',
	EnterAmount: 'Enter new amount',
	NoticeUpdated: "Notice updated successfully",
	Select: "Select",
	Private: "Private",
	EditNotice: "Edit Notice",
	UpdateNotice: "Update Notice",
	ArchiveNotice: "Archiving will remove this notice immediately",
	Information: "Information",
	SocietyWorkers: "Workers",
	ContactDirectoryMsg: "Contact information of residents within the society, who have signed up on the app",
	SocietyWorkersMsg: "Active list of plumbers, electricians and other workers available nearby",
	InfoLastUpdated: "Last updated on: ",
	SocietyCode: "Access Code",
	ViewAttachment: "View Attachment",
	WorkerSearchPlaceholder: "Search by name or number",
	Optional: "Optional",
	WorkerType: "Worker Skill or Type",
	WorkerTypePlaceHolder: "Plumber, wood wood worker etc",
	EditWorker: "Edit Worker",
	WorkerInfoUpdated: "Worker information updated",
	Image: "Image (Optional)",
	AddWorker: "Add Worker",
	UpdateWorker: "Update Record",
	Submit: "Submit",
	Guidelines: "Guidelines",
	GuidelinesMsg: "General rules and regulations for society members to follow.",
	DueDates: "Due Dates",
	BulkMaintenance: "Bulk Maintenance",
	PerHouse: "Per House",
	AddMaintenance: "Add Maintenance",
	Month: "Month",
	MonthNames: "January February March April May June July August September October November December",
	Houses: "Houses",
	MaintenanceRecieved: "Maintenance Received",
	DueDates: "Due Dates",
	Collections: "Collections",
	WorkersLeaves: "Workers Leaves",
	AddLeaveRecord: "Add Leave Record",
	SearchPlaceholder: "Quick Search",
	Name: "Name",
	Optional: "Optional",
	OperationSuccess: "Record was added successfuly",
	EditExpense: "Edit Expense",
	DownloadComplete: "Download complete",
	DownloadFailed: "Download failed",
	Downloading: "Downloading file..."
};